version: '3.9'


services:
  app:
    build: .
    container_name: subb-app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/eventdb
      - mongo
    restart: always


  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    restart: always


volumes:
  mongo-data: